services:
  miniocrud:
    image: ${DOCKER_REGISTRY-}miniocrud
    build:
      context: .
      dockerfile: MinIOCRUD/Dockerfile
    container_name: minio_crud_api
    ports:
      - "5000:8080"

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: miniocrud-minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    container_name: miniocrud-postgres
    restart: always
    environment:
      POSTGRES_DB: filecrud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  minio_data:
  pgdata:
